studies:
  -
    study_set_name: PAIRED_BOYDEN
    study_name: paired_boyden32c
    recording_names:
      - "1103_1_1"
      - "419_1_7"
      - "419_1_8"
      - "509_1_1"
      - "509_1_2"
      - "513_1_1"
      - "513_1_2"
      - "513_2_2"
      - "513_2_3"
      - "531_2_1"
      - "531_2_2"
      - "624_2_1"
      - "624_2_2"
      - "624_5_1"
      - "624_5_2"
      - "915_10_1"
      - "915_17_1"
      - "915_18_1"
      - "915_8_1"